spring:
  application:
    name: CareBridgeAdminAPI

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:13306/caredb
    username: careuser
    password: careuser

    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      connection-timeout: 10000

mybatis:
  mapper-locations: classpath:mapper/**/*.xml

logging:
  level:
    com.zaxxer: info
    org.springframework: info